version: '3.3'

services:
  dotnet-watch-docker-example:
    container_name: dotnet_watch_docker_example
    image: dispersia/dotnet-watch-docker-example
    build:
      context: .
    ports:
      - 5000:5000
    volumes:
      - './:/app'